services:
  - type: web
    name: restitch
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn restitch:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: restitch-db
          property: connectionString

databases:
  - name: restitch-db
    databaseName: restitch
    user: restitch